# Generated by Django 3.1.5 on 2024-05-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0005_auto_20240527_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='Categories', to='blogging.Post'),
        ),
    ]
